services:
  protonmail-bridge:
    image: ghcr.io/wormi4ok/protonmail-bridge:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 1143:143/tcp
      - 1025:25/tcp
    volumes:
      - protonmail:/root
volumes:
  protonmail:
    name: protonmail
